### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by valdadyne** [season-7/group_neutral_coders#1]
Hi guys, I created an alternative version but pushing it to a new branch has become a bigger challenge. I deleted the "alternative" branch I had created as it looked quite terrible. In my brackets local installation the site is running fine.

Please see attached files, see if you can figure it out.

[alternative_group_neutral_coders.zip](https://github.com/season-7/group_neutral_coders/files/309857/alternative_group_neutral_coders.zip)

**Comment by Harrisonkamau** [comment]
Thanks Gitau.
I'll look into it.

Happy coding!
